// table: games takes id (generated by script)
// table: linkgames takes primary_game and linked_game
// create entry in linkgames for every linked game (so a game with 5 more like this would have 5 link game entries)
// just realized I forgot the join table for tags so that needs to be added to the schema!

const mysql = require('mysql');
const mysqlConfig = {
  host: 'localhost',
  user: 'root',
  password: '',
  database: 'morelikethis'
};
const connection = mysql.createConnection(mysqlConfig);

const insertTags = (tagsArray, cb) => {
  for (var i = 0; i < tagsArray.length; i++) {
    connection.query('INSERT INTO tags (tag) VALUES (?)', [tagsArray[i]], (err, result) => {
      if (err) {
        cb(err);
      } else {
        console.log(result);
        cb(null, result);
      }
    });
  }
}


const newGame = (id, tags, cb) => {
  var queryString = ('INSERT INTO games (id) VALUES (?)');
  // var queryArgs = ([id]);
  connection.query(queryString, [id], function(err, result) {
    if (err) {
      cb(err);
    } else {
      // console.log(result);
      newGameTags(id, tags, cb);
      cb(null, result);
    }
  });
}

const newGameTags = (id, tags, cb) => {
  var queryStringTags = ('INSERT INTO games_tags (game, tag) VALUES (?, ?)');
  for (var i = 0; i < tags.length; i++) {
    var currentTagId;
    connection.query('SELECT id FROM tags WHERE tag = ?', [tags[i]], (err, result) => {
      if (err) {
        console.log('error');
      } else {
        currentTagId = result[0].id;
      }
      var queryArgsTags = ([id, currentTagId]);
      connection.query(queryStringTags, queryArgsTags)
    });
  }
}

module.exports = {
  newGame, newGameTags, insertTags
}



// connection.query('select id from tags where tag = ?', [tags[i]], (err, result) => {
//   if (err) {
//     console.log(err);
//   } else {
//     console.log('game #', id, 'and tag is', tags[i], 'result is', result);
//   }
// });
// console.log('currentTag:', currentTag);
// connection.query(queryStringTags, [id, currentTag], (err, result) => {
//   if (err) {
//     cb(err);
//   } else {
//     console.log(result);
  // cb(null, result);
// }
// })